openedx/XBlock

xblock/core.py
xblock/mixins.py
xblock/test/test_core.py
xblock/test/test_mixins.py

@cdodge, @chrisndodge & maybe @mattdrayer  - Please review and then I'll open up to a wider. This is the base implementation of the IndexInfoMixin to be used for XBlocks to override when providing index information.

index_view exposable in XBlocks

---

AUTHORS
doc/guide/xblock.rst
xblock/fields.py
xblock/test/test_fields.py
xblock/test/test_fields_api.py

Provide ability to set field to a unique string by default.
This patch makes it possible to set a field's default value to a unique string that appears random, but is deterministically calculated for a field in the given scope:
my_field = xblock.fields.String(default=xblock.fields.UNIQUE_ID, ...)
It provides an alternative approach to callable defaults as discussed at https://github.com/edx/XBlock/pull/247. It was also discussed in https://groups.google.com/forum/#!topic/edx-code/eRZtQ7t4JJY.
- Partner information: 3rd party-hosted open edX instance, for an edX solutions client (so will need to get some sort of solution merged in)
- Merge deadline: 30th November (soft requirement to minimize code drift, we maintain it on the client fork in the meantime)

Provide ability to set field to a unique string by default.

---

xblock/core.py
xblock/plugin.py

Right now, if an XBlock is broken, you get a silent failure, with no way to debug, no way to know. Things just randomly don't show up or work. 
This PR gives the option to disable that. I'll make a mating PR to xblock-sdk.

You can disable silent failures

---

xblock/mixins.py
xblock/runtime.py
xblock/test/test_parsing.py

**Description**: This is a simple change to ignore comments when parsing XML *using the default parser built into XBlock*. Currently, if the XML includes comments, an error will result and the XBlock tree construction fails. For example, right now in general you cannot put comments into xblock-sdk workbench scenarios.
**Use cases**:
* Adding explanatory comments to course exports or workbench scenarios
* Temporarily disabling blocks in XML by commenting them out
* Some XBlocks currently have an "editor" interface that's just a big XML field where users can edit the XML that defines them and their child blocks. We currently have to override the `parse_xml` method in each such block to add code to ignore comments in order to avoid errors when users add them as part of an edit.
**Affects**: …

Ignore comments when parsing XML

---

README.rst
setup.py

The code in this repository used to be licensed under the AGPL license, but it was switched to the Apache 2.0 license in #231. Looks like we missed a few references, though. @nedbat, can you review this?

Clarify Apache 2.0 license

---

doc/getting_started.rst

@nedbat @mhoeber please review
These links were to pages that have been moved from edx-platform to edx-documentation.  I've updated them to point to the right place.

Fix links in getting_started.rst

---

xblock/mixins.py
xblock/test/test_parsing.py

**Description:** This PR fixes the issue with importing-exporting XBlocks, containing List and Dict XBLock fields.
**Background:** Previously, xml export code relied on the fact that python list and dict string representation matches json array and dictionary notation. This is true unless unicode items, keys or values are present - in such a case they are serialized as `u'label'` instead of `'label'`, and subsequent import fails.
**JIRA Tickets:** [SOL-574](https://openedx.atlassian.net/browse/SOL-574), [SOL-575](https://openedx.atlassian.net/browse/SOL-575), [OSPR-496](https://openedx.atlassian.net/browse/OSPR-496)
**Related:** edx-solutions fork get's [dedicated fix](https://github.com/edx-solutions/XBlock/commit/54eb39cf8eb45c2adeb412cc784e989d8e3693e8) as part of birch migration. …

Fixed exporting List and Dict with unicode contents

---

xblock/fields.py
xblock/test/test_fields.py
xblock/test/test_fields_api.py

**Background and Motivation:** edx-platform import routine includes updating xblock location and explicitly [setting some fields to their values](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/modulestore/xml_importer.py#L1160-1171) in order to mark them as dirty (note the comment). However, this found to be wrong, as MUTABLE fields (e.g. `List` and `Dict`) are marked as dirty [*on read*](https://github.com/edx/XBlock/blob/master/xblock/fields.py#L490-491). As a result, setting mutable field to the same value does not mark it as dirty, as ["baseline"](https://github.com/edx/XBlock/blob/master/xblock/fields.py#L419) was just set to the same value. This, in turn, breaks importing later, but only for drafts, as published versions does not pass through …

EXPLICITLY_SET always overrides _dirty_fields content

---

xblock/fields.py
xblock/test/test_fields.py

[TNL-2686](https://openedx.atlassian.net/browse/TNL-2686)
If the xml attribute is setting using lxml library with ```None``` value then it raises ```TypeError``` ,  instead of passing ```None``` value to ```set(attribute, value)``` function , we can pass ```empty``` string (in case of NoneType) to avoid this error.
Test for the pr are at [#8889](https://github.com/edx/edx-platform/pull/8889)

return empty string if value is none

---

xblock/fields.py
xblock/test/test_fields.py

**Description**
The old version of these methods was inherently assymmetric.  The deserialisation in `from_string()`
only called `from_json()` when `enforce_type()` was overridden to do so (which all classes with a
non-trivial `from_json()` implementation do) and `enable_enforce_type` was set to `True`.  This commit
makes the two functions more consistent by not considering `enable_enforce_type` at all for
deserialisation and calling `from_json()` in `enforce_type()` by default.  Serialisation and
deserialisation requires correct types to work already, so there is no harm in always enforciing
the type – the code fails in the same cases as before.
This commit fixes a bug in serialising `DateTime` fields.  The old version included spurious double
quotes around the string, which would not be …

Make Field.to_string() and Field.from_string() methods more consistent.

---

AUTHORS
requirements.txt
xblock/exceptions.py
xblock/mixins.py

[TNL-2324](https://openedx.atlassian.net/browse/TNL-2324)
Adding message in `XBlockSaveError` excception. Current exception in [mixins.py#L275](https://github.com/edx/XBlock/blob/111935cab69a9128948180e6b9673c391d2ff165/xblock/mixins.py#L275) doesn't log the fields on which the error is occurring. 
```
Traceback (most recent call last):
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/newrelic-2.46.0.37/newrelic/hooks/framework_django.py", line 499, in wrapper return wrapped(*args, **kwargs)
File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 945, in handle_xblock_callback return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)
File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render. …
```

Adding message in XBlockSaveError Exception

---

xblock/fields.py
xblock/mixins.py
xblock/test/test_mixins.py

**Description:** This PR adds an option to force export any field. Forward-port of https://github.com/edx-solutions/XBlock/pull/6
The motivation is the following: `UNIQUE_ID` sentinel is used to generate a unique pseudo-random value for an XBlock field. The value generated is not actually random, and is stable (i.e. subsequent calculations return same value for given field and XBlock instances). The problem though, is that this value is not persisted in export-import workflow.
Direct motivation, more details and discussion of various approaches can be seen in the appropriate [JIRA task](https://edx-wiki.atlassian.net/browse/MCKIN-3637)
**JIRA Task:** [MCKIN-3637](https://edx-wiki.atlassian.net/browse/MCKIN-3637) and [OSPR-970](https://openedx.atlassian.net/browse/OSPR-970)
**Testing …

Force export runtime option + some tests for XmlSerializationMixin

---

django_requirements.txt
doc/fields.rst
requirements.txt
setup.py
xblock/reference/plugins.py

This PR makes pyfilesystem *field* support into a supported feature.
It explicitly does *not* mark the associated XBlock *service* API production-quality.
It is a minimal PR. It adds djpyfs as a dependency. It removes code for handling when it is not there. It removes comments marking this as prototype. It slightly shifts things around in the file to move the service as not finalized, but the field as finalized.
@cpennington @nedbat @ormsbee Would any two of you care to give this a thumbs up?

Making filesystem part of core XBlocks

---

xblock/mixins.py
xblock/test/test_fields.py
xblock/test/test_mixins.py

**Description:** forward-port of corresponding [solutions PR](https://github.com/edx-solutions/XBlock/pull/7). It is possible to set DateTime field to None (and not default), but exporting the course would fail in that case. This PR fixes this.
**JIRA:** [OSPR-1038](https://openedx.atlassian.net/browse/OSPR-1038)
**Testing Instructions:**
1. Create an XBlock with DateTime field (or use existing one).
2. (Optional) Using StudioEditableXBlockMixin from xblock-utils makes it much easier by providing declarative interface to specifying what fields should be edited.
3. In studio, add the block to a course.
4. Set DateTime field to empty value (if using StudioEditableXBlockMixin - set any value with datetime dropdown, than clear it with backspace/delete. Do **not** reset to default.
5. Try …

Fixing exporting DateTime with value set to None

---

script/max_pylint_violations
xblock/fields.py
xblock/mixins.py
xblock/test/test_core.py
xblock/test/test_mixins.py
xblock/test/test_parsing.py

https://openedx.atlassian.net/browse/PLAT-736
See related PR: https://github.com/edx/edx-platform/pull/11490
Add ability to send a String field value of `None` to the XBlock's XML representation using a XML attribute on a XML element. Deserialize the `None` value upon loading from XML. Add more testing around String fields with different defaults.
Also, fix a bug with caching the default value after deleting an XBlock field.
@cpennington @adampalay Please review. Anyone else that should review?
@macdiesel FYI.

Support XML serialization of None for String field.

---

AUTHORS
xblock/core.py
xblock/mixins.py
xblock/test/test_mixins.py

This PR is related with the conversation: https://github.com/edx/edx-platform/pull/11808#discussion_r56330814
`has_children` attribute is set in [ChildrenModelMetaclass](https://github.com/edx/XBlock/blob/master/xblock/mixins.py#L333) metaclass. `ChildrenModelMetaclass` is metaclass for [HierarchyMixin](https://github.com/edx/XBlock/blob/master/xblock/mixins.py#L355). `XBlock` inherits `HierarchyMixin`:
```
class XBlock(XmlSerializationMixin, HierarchyMixin, ScopedStorageMixin,
RuntimeServicesMixin, HandlersMixin, IndexInfoMixin, ViewsMixin, SharedBlockBase):
```
but `XBlockAside` isn't:
```
class XBlockAside(XmlSerializationMixin, ScopedStorageMixin, 
RuntimeServicesMixin, HandlersMixin, SharedBlockBase):
```
The `self.has_children` check is used in …

Fix XBlockAside.add_xml_to_node crash

---

setup.py
xblock/core.py

This builds on #340 and actually exposes a method to check the configured resources directory of a given XBlock.

Expose the configured resources_dir via get_resources_dir.

---

requirements.txt
setup.py
xblock/field_data.py

1. The 'pyyaml requirement is undeclared in setup.py
2. 'requests' is declared in 'requirements.txt' while it is in fact unused 
3. The 'has' method of the FieldData class should not be considered as abstract

Fix xblock requirements & non abstract FieldData method

---

xblock/fields.py
xblock/test/test_fields.py

https://openedx.atlassian.net/browse/PLAT-1031
If a control character exists in an XBlock String field that is then sent to XML, a ValueError is raised. This error blocks a course with control characters in video display_names (for example) from being exported. A simple example of the problem:
```
>>> from lxml import etree
>>> xml = etree.Element('my_element')
>>> string_field = u'Control Characters: "What to do \vabout them?"'
>>> string_field
u'Control Characters: "What to do \x0babout them?"'
>>> xml.set('my_attr', string_field)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "lxml.etree.pyx", line 744, in lxml.etree._Element.set (src/lxml/lxml.etree.c:44335)
File "apihelpers.pxi", line 554, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:19531) …
```

Remove control characters in XBlock String fields.

---

setup.py

Bump XBlock module version number to release the changes merged in this PR: 
https://github.com/edx/XBlock/pull/351
Forgot to add a version bump to the PR above - oops.
@macdiesel @jmbowman Please review.

Bump version number from 0.4.10 to 0.4.11

---

setup.py
xblock/mixins.py
xblock/test/test_core.py

https://openedx.atlassian.net/browse/TNL-5000
Add a test around unicode expectations in handlers.
Fixes changes introduced in this commit:
https://github.com/edx/XBlock/commit/4379a7e7040b51771a20e53d9fbb5472db7c02f3
@nedbat @cahrens @cpennington Please review.
@ssemenova @robrap  FYI.

Fix simplejson usage and unicode parsing.

---

xblock/plugin.py

Fixed typo in comment

---

README.rst

It looks like python 3 compatibility was added four months ago: https://github.com/edx/XBlock/commit/4700c7cb5b05fbfbea7d125525b681f9bccc23c3
And XBlock is now being tested by travis in 2.7 and 3.5.

Update readme for python3 compatibility

---

.travis.yml

As @clintonb recommended, removing `branches => only -> master` to get it to build on tags.
Also, the condition will run this on just one of the sub-builds in Travis.
See the Travis build for the test tag I created:
https://travis-ci.org/edx/XBlock/builds/303211533
FYI: @feanil @fredsmith @clintonb

Fix Travis deploy to PyPI for new tags.

---

.travis.yml
Makefile
requirements.txt
script/max_pylint_violations
setup.cfg
tox.ini
xblock/completable.py
xblock/test/settings.py
xblock/test/test_fields_api.py

Removed obsolete (and unused) TEMPLATE_* settings.  I also noticed that we haven't been running quality checks in Travis for a while due to a tox environment name mismatch; I broke those out into a separate tox environment and fixed the minor new issues it reported.  The violation threshold did increase by one, due to a new `FIXME` comment in `xblock/test/test_core.py` which will take some investigation (and possibly a switch to pytest) to resolve.

PLAT-1413 Remove obsolete TEMPLATE_* settings

---

tox.ini

The workaround for pytest finding tests both in the root directory and the installed packages left the collected coverage data file in the wrong place.  Move it where expected and see if this fixes codecov reports.

Fix codecov data reporting

---

openedx.yaml
setup.py

We had already updated tox and Travis to test against Python 3.6, but had not yet updated the trove classifiers or openedx.yaml to reflect this.  Doing so now.

Declare OEP-7 compliance

---

tox.ini
xblock/fields.py

XML doesn't require us to remove as many characters as we were.  This sanitization appeared as a hot spot in profiling the LMS.  This makes it much faster (20x?)

A faster sanitization of text

---

requirements/dev.txt
requirements/test.in
requirements/test.txt

Upgraded dependencies via `make upgrade` after changing the requirement.

chore: Remove old path.py dependency, which has been renamed as 'path'.

---

README.rst

Simple fix in the README to remove mention of Python2.7, since XBlock no longer supports it, and also update 3.5 to 3.8.

Remove Python 2.7 support from README

---

.github/workflows/ci.yml
tox.ini

Version 2 of the codecov uploader needs a coverage.xml file to upload.  This change adds a "coverage xml" step to create the file.

build: use v2 of the codecov action

---

requirements/pip-tools.txt

This failure started happening in the automated requirements upgrade:
https://github.com/openedx/XBlock/runs/5100983778?check_suite_focus=true
The bug was being caused by an interaction between pip and pip-tools, described here:
https://github.com/jazzband/pip-tools/issues/1558
The bug is fixed in pip-tools==6.5.0 - from this PR:
https://github.com/jazzband/pip-tools/pull/1567
Just bump the version manually to get the automated upgrades working again.

Manually upgrade pip-tools to 6.5.0 to fix pip/pip-tools bug.

---

setup.py
xblock/__init__.py

Adding required package dependencies in the setup.py file after syncing it up with [base.in](https://github.com/openedx/XBlock/blob/master/requirements/base.in)
root cause found after the following test case failure:
https://github.com/openedx/DoneXBlock/actions/runs/6433150390/job/17469600711?pr=178#step:6:41
Ideally, we should add all the base.in packages in the `install_requires` of `setup.py` by code like [this](https://github.com/openedx-unsupported/xblock-utils/blob/master/setup.py#L139), can do it next PR.

Update setup.py, adds required packages

---

.readthedocs.yaml

The `os` setting is now required for builds.

build: Fix docs build.

---

CHANGELOG.rst
xblock/__init__.py
xblock/core.py
xblock/runtime.py
xblock/test/test_core.py
xblock/test/test_runtime.py

Support for [OEP-58 JavaScript translations](https://docs.openedx.org/en/latest/developers/concepts/oep58.html):
-   Introduced abstract JavaScript translations support by adding the `i18n_js_namespace` property and `get_i18n_js_namespace` method to the `SharedBlockBase`. This allows XBlocks to define a JavaScript
namespace so the XBlock i18n runtime service can manage and load JavaScript translations for XBlocks.
-   Added the stub `get_javascript_i18n_catalog_url` method to the `NullI18nService` class to be implemented by runtime services.
-   See the [edx-platform atlas translations proposal](https://github.com/openedx/edx-platform/blob/master/docs/decisions/0019-oep-58-atlas-translations-design.rst)
This pull request blocks the platform PR:
- …

feat: add catalog url and js namespace for OEP-58 JS translations | FC-0012

---

.github/workflows/upgrade-python-requirements.yml

In a typical use case, modifying the `master` branch on a fork is not desired.

build: do not run the upgrade action on forks

---

CHANGELOG.rst
xblock/__init__.py
xblock/runtime.py
xblock/test/test_runtime.py

To match the Open edX LMS XBlockI18nService in test environments. Otherwise, tests in individual XBlock repositories will fail due to an incorrect definition in:
- https://github.com/openedx/XBlock/pull/691
This does _not_ affect production code but it's blocking other pull requests from getting merged:
- https://github.com/openedx/xblock-drag-and-drop-v2/pull/365
Already tested and works with:
- https://github.com/openedx/xblock-drag-and-drop-v2/actions/runs/7303777534/job/19904885323
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).

fix: add missing ``xblock`` parameter in `get_javascript_i18n_catalog_url` | FC-0012

---

CHANGELOG.rst
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/test.txt
xblock/__init__.py
xblock/core.py
xblock/test/test_core.py

According to [these warnings](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/xblock/runtime/shims.py), we should eventually make these updates across the board:
* `block.location` -> `block.scope_ids.usage_id`
* `block.course_id` -> `block.scope_ids.usage_id.context_key`
The thing is... these new names are (subjectively, of course) not very good 😄 They take longer to type out, they take up more space on a line, and IMO are more intimidating to devs who don't have their heads way into XBlock land. Every time I update code from `location` or `course_id` to the new, longer name, I find the resulting line harder to read. It also took me a long time to remember whether to use `id` versus `key`, which is maddeningly inconsistent in the phrase …

feat: XBlock.usage_key, XBlock.context_key convenience props

---

requirements/ci.txt
requirements/dev.txt
requirements/django.in
requirements/django.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/test.txt

We were explictly pinning django in django.in which is not necessary and makes it so your dev environment runs with and old version of django. The correct pin already exists in the common-constraints.txt file in edx-lint so we don't need to have an explicit pin here.  And for testing, the version is controlled via tox so it doesn't use this. It does effect dev and doc environments though so we should keep it up to date and make it harder to pin it in correctly.

Unpin the Django dependency

---

CHANGELOG.rst
xblock/__init__.py
xblock/fragment.py
xblock/test/test_fragment.py

This fix: #680  
created issues in the following xblocks:
The following xblocks on edX need to be updated:
Oppia-xblock (currently archived and read only, https://github.com/edx/oppia-xblock )
schoolyourself (https://github.com/openedx/schoolyourself-xblock )
imagemodal (https://github.com/openedx/xblock-image-modal )
invideoquiz (https://github.com/openedx/xblock-in-video-quiz )
concept (https://github.com/openedx/ConceptXBlock )
audio (https://github.com/openedx/AudioXBlock )
animation (currently archived and ready only, https://github.com/openedx-unsupported/AnimationXBlock )
Therefore, rather than change all of these, we needed to expeditiously find a solution, which is reverting the depr in this case. The added pain of the passthrough is outweighed by the lift to play whack-a-mole on …

feat: re-add fragment as passthrough to webfragement.fragment

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml
.readthedocs.yaml
CHANGELOG.rst
README.rst
docs/xblock-tutorial/getting_started/prereqs.rst
setup.py
tox.ini
xblock/__init__.py
xblock/core.py
xblock/plugin.py
xblock/test/test_core.py
xblock/test/utils/test_resources.py
xblock/utils/resources.py

- Drop Py3.8 support 
- Replace pkg_resources lib with importlib.resources
Ticket: https://github.com/openedx/XBlock/issues/676
**Followed migration guide:** 
https://importlib-resources.readthedocs.io/en/latest/migration.html
**Testing:**
I have tested the changes with following steps:
1. Use [PR](https://github.com/openedx/xblock-sdk/pull/350) of `xblock-sdk`
2. Install `xblock` into `xblock-sdk`
3. Install `feedback-xblock` from [PR](https://github.com/openedx/FeedbackXBlock/pull/58) into `xblock-sdk`
4. Test feedback xblock functionality

Drop py3.8 support | Replace pkg_resources lib with importlib.resources

---

setup.py

Fix pypi error related to long_description
``` shell
ERROR    `long_description` has syntax errors in markup and would not be        
rendered on PyPI.                                                      
No content rendered from RST source.   
```
Error logs: https://github.com/openedx/XBlock/actions/runs/10089577081/job/27897375669#step:7:18
Fix reference: https://github.com/pypa/gh-action-pypi-publish/issues/162#issuecomment-1596104938

fix: Fix pypi error related to long_description

---

MANIFEST.in
README.rst
xblock/core.py
xblock/fields.py
xblock/utils/helpers.py

This will make some changes in the readme file and fixes some typos in the code.

fix: cleanup

---

CHANGELOG.rst
docs/xblock-tutorial/edx_platform/index.rst
docs/xblock-tutorial/edx_platform/overrides.rst
xblock/__init__.py
xblock/plugin.py
xblock/test/test_plugin.py

Add ability to override another XBlock with the `xblock.v1.overrides` entrypoint. 
- Fixes #777 which removed our current hack for overriding existing XBlock behavior with a plugin.
- See [conversation here](https://discuss.openedx.org/t/override-default-edx-platform-xblock-mappings-without-forking/12441/) for historical context & reasoning.
``` python
setup(
entry_points={
"xblock.v1.overrides": [
"html = my_new_repo.my_new_block:HtmlBlock",
"problem = my_new_repo.my_new_block:ProblemBlock",
"video = my_new_repo.my_new_block:VideoBlock",
],
}
)
```

feat: XBlock overrides

---

xblock/__init__.py
xblock/plugin.py

Checking the entrypoints for the XBlock class we want for a given tag name is relatively expensive. We mitigate this by caching the mapping of tags to classes in Plugin.load_class(). But before this commit, we weren't caching failed lookups, i.e. the situation where there is no XBlock that maps to a given tag. This meant that if a course had many instances of a type of XBlock that is not installed on the given server, we would be constantly scanning entrypoints to look for our non-existent XBlock subclass. This really slows down things like the Studio course outline page.
The fix here is to store failed lookups as None values in the PLUGIN_CACHE.

perf: cache missing XBlock mappings in load_class

---

README.rst
catalog-info.yaml
docs/links.rst
docs/xblock-tutorial/concepts/runtimes.rst

Convert links from edx.readthedocs.io to links on docs.openedx.org
The installing & configuring guide is not yet moved, so those links are currently unchanged. Ref https://github.com/openedx/docs.openedx.org/issues/830

docs: Update edx.rtd.io links to docs.openedx.org

---

docs/xblock-tutorial/glossary.rst

We migrated docs.openedx.org to have one unified glossary.

docs: Update an intersphinx link after an upstream update.

---

docs/xblock-tutorial/glossary.rst

Sumac docs are failing to build due to this issue. Backport to Sumac. Ref #825

Update intersphinx link (Sumac backport)

---

catalog-info.yaml
docs/links.rst

- **docs: Include XBlock as part of named releases** ref: https://github.com/openedx/axim-engineering/issues/1420
- **docs: Update link to Installing and Configuring guide** ref: https://github.com/openedx/edx-documentation/issues/2339

Update catalog-info; update a RTD link

---

catalog-info.yaml

This repo was previously tagged for release only to facilitate docs builds. As it is a transitive dependency, it should not be tagged for release. Please see openedx/docs.openedx.org#941 for more detail.

build: Untag this repo for release

---

.github/workflows/ci.yml
CHANGELOG.rst
setup.py
tox.ini
xblock/__init__.py
xblock/test/settings.py

- Resolves https://github.com/openedx/XBlock/issues/832
[The USE_L10N setting will be removed](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-5-0).

Add support for Django 5.2
