openedx/XBlock

AUTHORS
doc/Makefile
doc/api/xblock.rst
xblock/mixins.py

I have just tweaked some sphinx-build arguments so that Sphinx builds the documentation when the source files are also changed.
Changed XBlock documentation to also show the inherited members and added few clarifications to the handlers' documentation.

Documentation updates

---

.travis.yml

@benpatterson @singingwolfboy Please review

update .travis.yml to only build once per PR

---

xblock/test/test_runtime.py

@sarina I think I have this right?

existent has an e, not an a

---

xblock/core.py
xblock/field_data.py
xblock/mixins.py
xblock/runtime.py
xblock/test/test_runtime.py

@doctoryes @alawibaba @utkjad: This should help optimize parent traversal.

Pass parent to xblock on load

---

xblock/core.py
xblock/mixins.py
xblock/test/test_mixins.py
xblock/test/test_runtime.py

@cpennington @ormsbee Please review.

Add "supports" functionality tagging on xBlock views.

---

xblock/fields.py
xblock/test/test_core.py
xblock/test/test_fields.py

See #309.
ping @sarina @cpennington

Add Set field

---

README.rst

So it looks nicer next to the travis badge. :)
cc @sarina, @singingwolfboy

Use svg coveralls badge

---

.travis.yml

Switch to the new travis infrastructure

---

xblock/fields.py
xblock/test/test_fields.py

[PLAT-736](https://openedx.atlassian.net/browse/PLAT-736)
Reverted the related pr [#8889](https://github.com/edx/edx-platform/pull/8889) on edx -platform produce issue [TNL-3031](https://openedx.atlassian.net/browse/TNL-3031).

Revert "String field return empty string for None"

---

doc/exceptions.rst
doc/fields.rst
doc/fragment.rst
doc/index.rst
doc/runtime.rst
doc/xblock.rst

@cpennington  or @nedbat   small addition that isn't user visible.  We are doing this across all doc to be able to use intersphinx to manage an obscene amount of links without hardcoding URLs.

Add labels to each topic

---

django_requirements.txt

Upgrade django version to 1.8.

---

setup.py
xblock/__init__.py

@macdiesel @nedbat FYI - please review, though I'll go ahead and merge this once tests pass.

Bump XBlock version from 0.4.4 to 0.4.5

---

requirements.txt
xblock/test/django/test_request.py

@mattdrayer @nedbat @doctoryes please review it. 
I make this change in order resolve the test failure issue in #335

webob version

---

xblock/core.py
xblock/test/test_runtime.py

@mattdrayer @nedbat please review the change set.

WL-376 move i18n runtime logic in parent XBlock

---

setup.py
xblock/__init__.py

mattdrayer/increment-release-version: Bump to 0.4.7

---

xblock/core.py
xblock/test/test_core.py

This feature lets an XBlock configure, precisely, where its public assets actually live on disk.  This is useful for a few reason:
- packages which have multiple XBlocks can separate the public folders for each XBlock to ensure isolation
- XBlocks can set the value to None which prevents them from having local_resource_url invoked on them period, which is useful for signalling that an XBlock should not be trying to even use resources
This is important for a few XBlock authors but also to allow an easier migration of XModules/XBlocks in the edx-platform to become freestanding instead of globbed together.

Add the ability to control the root where resources load from.

---

.travis.yml

Coveralls is blocking a couple PRs for me. (#349,  #357)
I've been given the go-ahead to switch to codecov.  Here's a PR.

Switch to codecov.

---

setup.py

Fixed the classifiers so that the package can be uploaded to PyPI.

Fix setup.py classifiers

---

xblock/__init__.py
xblock/exceptions.py
xblock/fields.py
xblock/test/test_core.py

Fix a few typos

---

requirements/dev.txt
requirements/django.txt
requirements/doc.txt
requirements/test.in
requirements/test.txt
requirements/travis.txt

[BD-18] remove nose footprints from the project

---

django_requirements.txt

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1948

Remove outdated requirements file

---

.github/pypi-publish.yml
.github/workflows/ci.yml

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2734

BOM-2734: Github Actions CI

---

.github/workflows/upgrade-python-requirements.yml

Do the requirements upgrade on Sundays so it's ready to review on Monday.

build: Update upgrade-python-requirements.yml cron

---

.github/workflows/ci.yml
CHANGELOG.rst
tox.ini
xblock/__init__.py

- Added support for Django 42
- Issue: https://github.com/edx/upgrades/issues/181

fix: Added support for Django42

---

.github/workflows/upgrade-python-requirements.yml

Update the team name to axim-engineering.

chore: Update upgrade-python-requirements.yml

---

docs/links.rst
docs/xblock-tutorial/anatomy/javascript.rst
docs/xblock-tutorial/anatomy/python.rst
docs/xblock-tutorial/customize/custom-html.rst
docs/xblock-tutorial/customize/custom-javascript.rst
docs/xblock-tutorial/customize/custom-python.rst
docs/xblock-tutorial/customize/custom-stylesheets.rst
docs/xblock-tutorial/edx_platform/edx_lms.rst
docs/xblock-tutorial/edx_platform/edx_studio.rst
docs/xblock-tutorial/reusable/code_myxblock_js.rst
docs/xblock-tutorial/reusable/code_myxblock_python.rst
docs/xblock-tutorial/reusable/code_thumbs_fields.rst
docs/xblock-tutorial/reusable/code_thumbs_student_view.rst

Mostly matching the Thumbs and MyXBlock code to the actual code you get when you make these blocks in the xblock sdk. Also some spelling fixes and clarifications.

Update customize section of XBlock tutorial

---

CHANGELOG.rst
xblock/__init__.py

This adds support for streaming responses: #737

chore: bump version to 4.1.0

---

README.rst

Closes https://github.com/openedx/XBlock/issues/740

Update README.rst around deploying.
